/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMemeCampaignManager,
  IMemeCampaignManagerInterface,
} from "../../../contracts/interfaces/IMemeCampaignManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "campaignId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "amount",
        type: "uint128",
      },
    ],
    name: "handlePostSwap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMemeCampaignManager__factory {
  static readonly abi = _abi;
  static createInterface(): IMemeCampaignManagerInterface {
    return new Interface(_abi) as IMemeCampaignManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMemeCampaignManager {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMemeCampaignManager;
  }
}
